# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PK48ryPvUTAErPu-8TlW7zFz0DVwu60
"""

import streamlit as st

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms import LlamaCpp

st.set_page_config(page_title="Bank Process Assistant", layout="wide")

st.title("🏦 Local Banking Process Assistant (8GB RAM Optimized)")

# Load embeddings
@st.cache_resource
def load_embeddings():
    return HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

# Load FAISS
@st.cache_resource
def load_db():
    embeddings = load_embeddings()
    return FAISS.load_local(
        "vectorstore",
        embeddings,
        allow_dangerous_deserialization=True
    )

# Load local Mistral (quantized GGUF)
@st.cache_resource
def load_llm():
    return LlamaCpp(
        model_path="models/mistral.gguf",
        temperature=0.1,
        max_tokens=1024,
        n_ctx=2048,
        n_threads=4,   # important for 8GB RAM CPU
        verbose=False
    )

db = load_db()
llm = load_llm()

question = st.text_input("Ask a question about banking processes")

if question:

    # 1. Retrieve documents
    docs = db.similarity_search(question, k=4)

    context = "\n\n".join([d.page_content for d in docs])

    # 2. Prompt engineering (very important for local model)
    prompt = f"""
You are a banking process expert.

Answer ONLY using the context below.
If not found, say: "Not found in internal procedures."

Context:
{context}

Question:
{question}

Answer clearly and structured:
- Process steps
- Departments involved
- Controls if available
"""

    # 3. Run local model
    response = llm.invoke(prompt)

    # 4. Output
    st.subheader("Answer")
    st.write(response)

    st.subheader("Sources")
    for i, doc in enumerate(docs):
        st.markdown(f"**Source {i+1}**")
        st.write(doc.page_content[:800])