# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PK48ryPvUTAErPu-8TlW7zFz0DVwu60
"""

import streamlit as st

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms import LlamaCpp

st.set_page_config(
    page_title="Bank Process Agent",
    layout="wide"
)

st.title("🏦 Banking Process Assistant (Local)")

# -------- Load embeddings --------
@st.cache_resource
def get_embeddings():
    return HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

# -------- Load FAISS --------
@st.cache_resource
def get_vectorstore():
    return FAISS.load_local(
        "vectorstore",
        get_embeddings(),
        allow_dangerous_deserialization=True
    )

# -------- Load local LLM --------
@st.cache_resource
def get_llm():
    return LlamaCpp(
        model_path="models/mistral.gguf",  # optional if you use local LLM
        n_ctx=2048,
        n_threads=4,
        temperature=0.1,
        verbose=False
    )

db = get_vectorstore()
llm = get_llm()

question = st.text_input("Ask a banking process question")

if question:

    # 1. Retrieve relevant chunks
    docs = db.similarity_search(question, k=4)

    context = "\n\n".join([d.page_content for d in docs])

    # 2. Prompt (very important for banking accuracy)
    prompt = f"""
You are a banking process expert.

Rules:
- Use ONLY the context below
- If not found say: "Not found in internal procedures"

Context:
{context}

Question:
{question}

Answer clearly:
- Steps
- Departments involved
- Controls (if any)
"""

    # 3. LLM inference
    answer = llm.invoke(prompt)

    # 4. Output
    st.subheader("Answer")
    st.write(answer)

    st.subheader("Sources")
    for i, d in enumerate(docs):
        st.markdown(f"**Source {i+1}**")
        st.write(d.page_content[:800])